# Generated by Django 3.2.7 on 2024-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=500)),
                ('linkedin_link', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='teams')),
                ('category', models.CharField(choices=[('academic_advisory_board', 'academic_advisory_board'), ('core_team', 'core_team')], default='core_team', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
