# Generated by Django 3.2.7 on 2025-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='designation',
            field=models.CharField(default='core_team', max_length=500),
        ),
    ]
