# Generated by Django 3.2.7 on 2025-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='designation',
        ),
        migrations.AddField(
            model_name='team',
            name='job_role',
            field=models.CharField(default='Full Time Engineer', max_length=500),
        ),
    ]
