# Generated by Django 3.2.7 on 2025-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20250805_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('academic_advisory_board', 'academic_advisory_board'), ('core_team', 'core_team'), ('core_team_and_TA', 'core_team_and_TA')], default='core_team', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='job_role',
            field=models.CharField(max_length=500),
        ),
    ]
