# Generated by Django 3.2.7 on 2025-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20250805_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='job_role',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
