# Generated by Django 3.2.7 on 2026-02-18 11:41

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('pdf', models.FileField(upload_to='course/assignments')),
                ('assignment_type', models.CharField(choices=[('mandatory', 'mandatory'), ('optional', 'optional')], default='mandatory', max_length=20)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('url_link_name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('course_description', models.TextField(blank=True)),
                ('course_image', models.ImageField(default='', upload_to='course/courses')),
                ('indian_fee', models.IntegerField(blank=True)),
                ('foreign_fee', models.IntegerField(blank=True)),
                ('level', models.CharField(max_length=255)),
                ('entire_overview', ckeditor.fields.RichTextField(blank=True)),
                ('access_description', ckeditor.fields.RichTextField(blank=True)),
                ('refund_description', ckeditor.fields.RichTextField(blank=True)),
                ('assignment_description', ckeditor.fields.RichTextField(blank=True)),
                ('brief_overview', ckeditor.fields.RichTextField(blank=True)),
                ('course_type', models.CharField(blank=True, max_length=255)),
                ('first_offered', models.CharField(blank=True, max_length=255)),
                ('current_status', models.CharField(blank=True, max_length=255)),
                ('user_engagement_per_week', models.CharField(blank=True, default='', max_length=255)),
                ('free_videos_link', models.CharField(blank=True, max_length=255)),
                ('optional_assignment_flg', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('enrolled_users', models.IntegerField(blank=True)),
                ('total_videos', models.IntegerField(blank=True, default=0)),
                ('assignments', models.IntegerField(blank=True, default=0)),
                ('discussion_forum_text', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_price', models.FloatField()),
                ('enrolled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('full_access_flag', models.BooleanField(default=False)),
                ('installment_id_2', models.CharField(blank=True, max_length=500, null=True)),
                ('installment_id_3', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_installments', models.IntegerField(default=1)),
                ('first_installments', models.BooleanField(default=False)),
                ('second_installments', models.BooleanField(default=False)),
                ('third_installments', models.BooleanField(default=False)),
                ('serial_number', models.CharField(blank=True, default='', max_length=500)),
                ('invoice', models.FileField(blank=True, default='', upload_to='Enroll_user/Invoice/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('socialaccount_link', models.CharField(blank=True, max_length=255)),
                ('role', models.TextField()),
                ('profile_picture', models.ImageField(default='', upload_to='course/instructors')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('module_overview', ckeditor.fields.RichTextField(blank=True)),
                ('part_number', models.IntegerField(blank=True, default=0)),
                ('welcome_description', ckeditor.fields.RichTextField(blank=True)),
                ('topics_covered', models.TextField(blank=True)),
                ('total_assignments', models.IntegerField(blank=True, default=0)),
                ('estimated_time', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('socialaccount_link', models.CharField(blank=True, max_length=255)),
                ('role', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(default='', upload_to='course/teaching-assistant')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('main_lectures', 'main_lectures'), ('ta_lectures', 'ta_lectures'), ('programming_lectures', 'programming_lectures')], default='main_lectures', max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('duration', models.CharField(default='', max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module')),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.video')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OverallProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=355)),
                ('sub_topics', ckeditor.fields.RichTextField(blank=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.CharField(default='', max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('course_amount', models.FloatField()),
                ('tax', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='New', max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.section'),
        ),
        migrations.CreateModel(
            name='Invoice_Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice', models.FileField(blank=True, upload_to='Invoice_users/')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.enrolleduser')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.order')),
            ],
        ),
        migrations.CreateModel(
            name='Failed_Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('submitted_file', models.FileField(default='', upload_to='course/submitted_assignments')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('submission_count', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment')),
                ('course', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.module')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.order'),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.payment'),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(blank=True, to='course.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistant',
            field=models.ManyToManyField(blank=True, to='course.TeachingAssistant'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module'),
        ),
        migrations.CreateModel(
            name='AssignmentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('submitted_file', models.FileField(default='', upload_to='course/submitted_assignments')),
                ('submit_flag', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment')),
                ('course', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'assignment')},
            },
        ),
    ]
