# Generated by Django 3.2.7 on 2026-03-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptioninvoice'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
    ]
