# Generated by Django 3.2.7 on 2026-03-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customplaylist', '0007_customplaylist_order_number'),
        ('course', '0002_order_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customplaylist.customplaylist'),
        ),
    ]
