# Generated by Django 4.2.30 on 2026-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_order_custom_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_of_installments',
            field=models.IntegerField(default=1),
        ),
    ]
