# Generated by Django 3.2.7 on 2026-07-15 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_order_no_of_installments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_score', models.FloatField(default=100.0, help_text='Maximum score admin can give (default 100)')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course.module')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
