# Generated by Django 3.2.7 on 2026-07-10 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_order_no_of_installments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses_purchased', models.IntegerField(default=0)),
                ('total_courses_completed', models.IntegerField(default=0)),
                ('total_learning_hours', models.FloatField(default=0.0)),
                ('total_study_minutes', models.FloatField(default=0.0)),
                ('total_assignment_score', models.FloatField(default=0.0)),
                ('average_assignment_score', models.FloatField(default=0.0)),
                ('total_assessment_score', models.FloatField(default=0.0)),
                ('average_assessment_score', models.FloatField(default=0.0)),
                ('current_learning_streak', models.IntegerField(default=0)),
                ('longest_learning_streak', models.IntegerField(default=0)),
                ('total_login_days', models.IntegerField(default=0)),
                ('total_modules_completed', models.IntegerField(default=0)),
                ('total_lectures_completed', models.IntegerField(default=0)),
                ('total_assignments_completed', models.IntegerField(default=0)),
                ('total_assessments_completed', models.IntegerField(default=0)),
                ('average_course_completion_days', models.FloatField(default=0.0)),
                ('overall_performance_score', models.FloatField(default=0.0)),
                ('internship_eligible', models.BooleanField(default=False)),
                ('student_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.FloatField(default=0.0, help_text='Time taken in minutes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectureActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('watch_duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_download_time', models.DateTimeField(blank=True, null=True)),
                ('assignment_submission_time', models.DateTimeField(blank=True, null=True)),
                ('admin_review_time', models.DateTimeField(blank=True, null=True)),
                ('marks', models.FloatField(default=0.0, help_text='0-100')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assignments', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(default='Unknown Assessment', max_length=255)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('passing_status', models.BooleanField(default=False)),
                ('time_taken', models.FloatField(default=0.0, help_text='Time taken in minutes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('access_start_date', models.DateTimeField(blank=True, null=True)),
                ('expected_course_duration', models.IntegerField(default=0, help_text='Duration in days')),
                ('expected_completion_date', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('completion_days', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('course_status', models.CharField(default='Not Started', max_length=50)),
                ('total_modules', models.IntegerField(default=0)),
                ('completed_modules', models.IntegerField(default=0)),
                ('total_lectures', models.IntegerField(default=0)),
                ('completed_lectures', models.IntegerField(default=0)),
                ('total_assignments', models.IntegerField(default=0)),
                ('completed_assignments', models.IntegerField(default=0)),
                ('total_assessments', models.IntegerField(default=0)),
                ('completed_assessments', models.IntegerField(default=0)),
                ('assignment_average', models.FloatField(default=0.0)),
                ('assessment_average', models.FloatField(default=0.0)),
                ('study_minutes', models.FloatField(default=0.0)),
                ('study_hours', models.FloatField(default=0.0)),
                ('discussion_posts', models.IntegerField(default=0)),
                ('discussion_replies', models.IntegerField(default=0)),
                ('login_days', models.IntegerField(default=0)),
                ('learning_streak', models.IntegerField(default=0)),
                ('course_performance_score', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='DailyLearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_time', models.FloatField(default=0.0, help_text='In minutes')),
                ('lectures_completed', models.IntegerField(default=0)),
                ('modules_completed', models.IntegerField(default=0)),
                ('assignments_submitted', models.IntegerField(default=0)),
                ('assessments_completed', models.IntegerField(default=0)),
                ('discussion_posts', models.IntegerField(default=0)),
                ('discussion_replies', models.IntegerField(default=0)),
                ('login_count', models.IntegerField(default=0)),
                ('daily_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
