# Generated by Django 3.2.7 on 2026-07-17 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentactivity',
            options={'verbose_name': 'Student Assignment Submission', 'verbose_name_plural': 'Student Assignment Submissions'},
        ),
        # Skip AlterUniqueTogether since constraint already exists in database
        migrations.DeleteModel(
            name='ModuleActivity',
        ),
    ]
