# Generated by Django 4.2.30 on 2026-07-17 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_analytics', '0002_auto_20260717_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseanalytics',
            name='access_source',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('subscription', 'Subscription')], default='purchase', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcourseanalytics',
            name='dels_contribution_weight',
            field=models.FloatField(default=0.0, help_text='Cached W_i from the last DELS run'),
        ),
        migrations.AddField(
            model_name='studentcourseanalytics',
            name='dels_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcourseanalytics',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DELSSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dels_value', models.FloatField(default=0.0)),
                ('tier', models.CharField(default='At Risk', max_length=20)),
                ('breakdown_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dels_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
