# Generated by Django 3.2.7 on 2026-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customplaylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customplaylist',
            name='include_assignments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voiceassessment',
            name='max_duration',
            field=models.IntegerField(default=60),
        ),
    ]
