# Generated by Django 3.2.7 on 2026-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customplaylist', '0002_auto_20260314_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='customplaylist',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
