# Generated by Django 3.2.7 on 2026-03-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customplaylist', '0003_customplaylist_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice', models.FileField(blank=True, upload_to='Invoice_users/playlists/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customplaylist.customplaylist')),
            ],
        ),
    ]
