# Generated by Django 3.2.7 on 2026-03-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customplaylist', '0004_playlistinvoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceAssessment',
        ),
    ]
