# Generated by Django 3.2.7 on 2026-03-18 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customplaylist', '0005_delete_voiceassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(default='Custom Playlist', max_length=100)),
                ('playlist_name', models.CharField(default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_id', models.CharField(max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_file', models.FileField(blank=True, upload_to='Invoice_users/playlists/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customplaylist.customplaylist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PlaylistInvoice',
        ),
    ]
