# Generated by Django 3.2.7 on 2026-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customplaylist', '0006_auto_20260318_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='customplaylist',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
