# Generated by Django 3.2.7 on 2026-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptioninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategoryaccess',
            name='category',
            field=models.CharField(choices=[('CAT-IA', 'CAT-IA'), ('CAT-IB', 'CAT-IB'), ('CAT-II', 'CAT-II')], max_length=20),
        ),
    ]
