# Generated by Django 3.2.7 on 2026-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plancategoryaccess_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancategoryaccess',
            name='category',
            field=models.CharField(choices=[('IA', 'IA'), ('IB', 'IB'), ('II', 'II')], max_length=20),
        ),
    ]
